# Generated by Django 5.1.3 on 2024-11-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('plot_no', models.CharField(max_length=30)),
                ('house_no', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'houses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='House_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('door_no', models.CharField(max_length=30, unique=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'House_info',
                'verbose_name_plural': 'House_infos',
                'db_table': 'house_infos',
                'ordering': ['door_no'],
            },
        ),
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('expected_rent_date', models.DateField()),
                ('rent_date', models.DateField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.house')),
                ('house_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='main.house')),
            ],
            options={
                'verbose_name': 'Renting',
                'verbose_name_plural': 'Rentings',
                'db_table': 'renting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=100)),
                ('checkout_request_id', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.renting')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
