# Generated by Django 5.1.3 on 2024-11-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_house_info_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house_info',
            options={'ordering': ['door_no'], 'verbose_name': 'House_info', 'verbose_name_plural': 'House_infos'},
        ),
        migrations.RenameField(
            model_name='house_info',
            old_name='Door',
            new_name='door_no',
        ),
    ]
