# Generated by Django 5.1.3 on 2024-11-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_house_info_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.house_info'),
        ),
    ]
