# Generated by Django 5.1.3 on 2024-11-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_renting_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renting',
            name='house_no',
        ),
        migrations.AlterField(
            model_name='renting',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='main.house'),
        ),
    ]
